import React from 'react';
import { Wrap, WrapItem, Tag } from '@chakra-ui/react';

export default function AboutMeTags() {
  return (
    <>
      <Wrap mt={2} spacing={2}>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="blue"
          >
            C
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="blue"
          >
            Python
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="blue"
          >
            JavaScript
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="blue"
          >
            React
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="red"
          >
            Express
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="green"
          >
            MongoDB
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="yellow"
          >
            Socket.io
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="orange"
          >
            JQuery
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="green"
          >
            MySQL
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="blue"
          >
            Javascript
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="yellow"
          >
            Webpack
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="purple"
          >
            Bootstrap
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="green"
          >
            Node
          </Tag>
        </WrapItem>      
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="purple"
          >
            Materialize
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="red"
          >
            HTML
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="orange"
          >
            CSS
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="green"
          >
            ChakraUI
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="yellow"
          >
            FramerMotion
          </Tag>
        </WrapItem>
        <WrapItem>
          <Tag
            size="sm"
            variant="subtle"
            colorScheme="green"
          >
            Firebase
          </Tag>
        </WrapItem>
      </Wrap>
    </>
  )
}
